// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Stocks",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Stocks",
            targets: ["AppModule"],
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "../StarJoin", from: "0.0.0"),
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: ["StarJoin"],
            path: ".",
            resources: [
                .process("./GameScene.sks"),
                .copy("./SampleData")
            ]
        )
    ]
)
